image: mcr.microsoft.com/dotnet/sdk:latest

build:
  stage: build
  script:
    - 'cd GestionStock'
    - 'dotnet build'
    - 'cd ../GestionStockTest'
    - 'dotnet build'

tests:
  stage: test
  script:
    - 'dotnet test'
