image: mcr.microsoft.com/dotnet/sdk:3.1.0

before_script:
  - 'dotnet restore GestionStock'
  - 'dotnet restore GestionStockTest'

stages:
    - Build
    - Test

GestionStock:
  stage: Build
  script:
    - 'dotnet build --no-restore GestionStock'
  allow_failure: false

GestionStockTest:
  stage: Build
  script:
    - 'dotnet build --no-restore GestionStockTest'
  allow_failure: false

UnitTests:
  stage: Test
  script:
    - 'dotnet test --no-restore GestionStockTest'
  allow_failure: false
