image: mcr.microsoft.com/dotnet/sdk:latest

before_script:
  - 'cd GestionStock'

build:
  stage: build
  script:
    - 'dotnet build'

tests:
  stage: test
  script:
    - 'cd ../GestionStockTest'
    - 'dotnet test'
