image: mcr.microsoft.com/dotnet/sdk:3.1

before_script:
  - 'dotnet restore GestionStock'
  - 'dotnet restore GestionStockTest'

stages:
    - Build
    - Test

GestionStock:
  stage: Build
  script:
    - 'dotnet build --no-restore GestionStock'
  allow_failure: false

GestionStockTest:
  stage: Build
  script:
    - 'dotnet build --no-restore GestionStockTest'
  allow_failure: false

UnitTests:
  stage: Test
  script:
    - 'dotnet test --no-restore GestionStockTest'
  allow_failure: false


sonarqube:
  stage : Test
  script: 
      - "apt-get update"
      - "apt-get install --yes openjdk-11-jre"
      - "dotnet tool install --global dotnet-sonarscanner"
      - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
      - "dotnet sonarscanner begin /k:\"BoisselNicolas_gestionstock_AX8C6T9s-GG3rbcPP0QT\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=http://0.0.0.0:9000\" "
      - "dotnet build"
      - "dotnet sonarscanner end /d:sonar.login=\"dfc7243c000f5ab803606d4207012ef793220e10\""
  allow_failure: true
  only:
    - master # or the name of your main branch


