image: mcr.microsoft.com/dotnet/sdk:latest

stages:
    - Build
    - Test

GestionStock:
  stage: build
  script:
    - 'dotnet build GestionStock'

GestionStockTest:
  stage: build
  script:
    - 'dotnet build GestionStockTest'

UnitTests:
  stage: Test
  script:
    - 'dotnet test GestionStockTest'
