language: csharp
mono: none
dotnet: 6.0
script:
  - 'dotnet restore GestionStock'
  - 'dotnet restore GestionStockTest'
  - 'dotnet build --no-restore GestionStock'
  - 'dotnet build --no-restore GestionStockTest'
  - 'dotnet test --no-restore GestionStockTest'
 